import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const VerifiedEmailList: string[] = [
  "sukhsharan7105@gmail.com",
  "harshiljadav28@gmail.com",
  "ejaz.j.chaudhary@gmail.com",
  "prathamsinh1@gmail.com",
  "ved.jp311@gmail.com",
  "malekmadina.123@gmail.com",
  "lipu10101010@gmail.com",
  "muskanmaster15@gmail.com",
  "pneel1924@gmail.com",
  "Harshiljadav28@gmail.com",
  "juwairiyyahsaiyed1803@gmail.com",
  "kypatel7338@gmail.com",
  "vedantrana92@gmail.com",
  "mayurpanchal2715@gmail.com",
  "aineemakwana23@gmail.com",
  "mouly068@gmail.com",
  "anshupal320@gmail.com",
  "ranarajveer65824@gmail.com",
  "mannchauhan1105@gmail.com",
  "dhrumilparmar27481@gmail.com",
  "Fuzailshaikh667@gmail.com",
  "Ejaz.j.chaudhary@gmail.com",
  "mahekgandhi2406@gmail.com",
  "arifasad860@gmail.com",
  "deeppatel0104@gmail.com",
  "saadtalati81@gmail.com",
  "smo.amanuddin12@gmail.com",
  "buxnadiya@gmail.com",
  "saniyapatel511@gmail.com",
  "manuwalarozana@gmail.com",
  "vekariya.krishna768@gmail.com",
  "sanjanabengamai123@gmail.com",
  "divuparmar65@gmail.com",
  "mannpatel7571@gmail.com",
  "hiralmehta495@gmail.com",
  "dshshbhm@gmail.com",
  "krishnamoghe74@gmail.com",
  "yugmistry1976@gmail.com",
  "contact.mzshaikh@gmail.com",
  "jainilpatel738@gmail.com",
  "nidhiyadavv41@gmail.com",
  "prabhatyadav99503@gmail.com",
  "hr9012454@gmail.com",
  "patelbinal1122004@gmail.com",
  "himanshusali57@gmail.com",
  "hinipatel8@gmail.com",
  "binitp2@outlook.com",
  "patelkrisha.110505@gmail.com",
  "kivinshipatel@gmail.com",
  "rajpatel76006@gmail.com",
  "vgamit637@gmail.com",
  "tejashchaudhari1807@gmail.com",
  "sp3896508@gmail.com",
  "rohan31054@gmail.com",
  "tandelkruti3011@gmail.com",
  "dhara08p@gmail.com",
  "khushikhan9095@gmail.com",
  "mayurkanzariya54854@gmail.com",
  "riyasolanki10818@gmail.com",
  "veer65patel@gmail.com",
  "vivekluckymanojsingh@gmail.com",
  "akshatchhatriwala@gmail.com",
  "akshu2885@gmail.com",
  "krishnajadav2804@gmail.com",
  "jinalahir2805@gmail.com",
  "220140107002@gtu.edu.in",
  "prathamsonara2005@gmail.com",
  "jasmin.patel2110@gmail.com",
  "prathamgujar82@gmail.com",
  "aphophale@gmail.com",
  "palakpatel2111am@gmail.com",
  "tripathiashwin2004@gmail.com",
  "pranavpardeshi21@gmail.com",
  "harshmistry662@gmail.com",
  "kswaraj822@gmail.com",
  "harekrishnapatra05@gmail.com",
  "bhuvamanoj03@gmail.com",
  "Prathamsinh1@gmail.com",
  "rajthakar1156@gmail.com",
  "preetishwarbhai7703@gmail.com",
  "02mihirt24@gmail.com",
  "hitgha137@gmail.com",
  "prathammote1407@gmail.com",
  "h.ykher.24@gmail.com",
  "nishitlad962@gmail.com",
  "patelprince2635@gmail.com",
  "patelutsav476@gmail.com",
  "machhihimanshu145@gmail.com",
  "rajbirari87@gmail.com",
  "shahmohit972@gmail.com",
  "220140107063@gtu.edu.in",
  "220140107047@gtu.edu.in",
  "parmarparam4@gmail.com",
  "fparmar163@gmail.com",
  "darshanparmarj2@gmail.com",
  "utsav9472@gmail.com",
  "rahul8033swain@gmail.com",
  "vekariyayash796@gmail.com",
  "soniprachi246@gmail.com",
  "riddhiraval1311@gmail.com",
  "kathankimehta10@gmail.com",
  "nehapsingh004@gmail.com",
  "riya.m.rana03@gmail.com",
  "shalinisingh123098@gmail.com",
  "shubhamdash254@gmail.com",
  "esharaval309@gmail.com",
  "patelmeshwa65@gmail.com",
  "sauravbarai2000@gmail.com",
  "kanaiyasoni688@gmail.com",
  "jpriyansh600@gmail.com",
  "officialboy9091@gmail.com",
  "j.mangrola076@gmail.com",
  "rudralad115@gmail.com",
  "ved.jp311@gmail.com",
  "binitp2@gmail.com",
  "yp511293@gmail.com",
  "dhirajkeshwani23@gmail.com",
  "mayurmakwana123.0@gmail.com",
  "zeeshankadiwala04@gmail.com",
  "fuzailshaikh667@gmail.com",
  "dhruvp462004@gmail.com",
  "beravivek26@gmail.com",
  "yashsharmaa2674@gmail.com",
  "ansh8112003@gmail.com",
  "sharma57sona@gmail.com",
  "paramjitsinhparmar21@gmail.com",
  "shreya77bhatt@gmail.com",
  "sonal2752004@gmail.com",
  "maazdaud000@gmail.com",
  "utsavp6075@gmail.com",
  "gunjalbpatel57@gmail.com",
  "parthchauhan4391@gmail.com",
  "Veer65patel@gmail.com",
  "rajpurohitmahima99@gmail.com",
  "rutx7ck11@gmail.com",
  "harshmodi1516@gmail.com",
  "sarvampatel953@gmail.com",
  "patelkaran20393@gmail.com",
  "j.mangrola077@gmail.com",
  "220140107010meetdhimmer@gmail.com",
  "divy.rathod.22@gmail.com",
  "chauhanurvesh1@gmail.com",
  "vatsalchauhan9804@gmail.com",
  "ahirmarmik@gmail.com",
  "hamzasheriwala786@gmail.com",
  "srinathshrestha9890@gmail.com",
  "patelparth8022@gmail.com",
  "akash7567245371@gmail.com",
  "setumadhavani@gmail.com",
  "deepkhatri050@gmail.com",
  "sehgalmilan29@gmail.com",
  "payalrana0606@gmail.com",
  "nehitbhesaniya212@gmail.com",
  "salokhe.sayee27@gmail.com",
  "abth110405@gmail.com",
  "vaidehithacker23@gmail.com",
  "sarfpatel204@gmail.com",
  "mohitsoni.25022005@gmail.com",
  "tishasoni022@gmail.com",
  "letsmeetimran@gmail.com",
  "smitp0058@gmail.com",
  "jiyan10102004@gmail.com",
  "kashyapdivyansh@ieee.org",
  "sakshiprajapati90903@gmail.com",
  "bugs.freelancer@gmail.com",
  "gohilruteshi@gmail.com",
  "manthandsoni@gmail.com",
  "trivedikhushi151@gmail.com",
  "pateljarmil@gmail.com",
  "vidhiee271@gmail.com",
  "kotvalbaban@gmail.com",
  "kapadiyashivansh@gmail.com",
  "pvedant1101@gmail.com",
  "mahijitendrasinh@gmail.com",
  "vaghelahv333@gmail.com",
  "vanshvyas0101@gmail.com",
  "ravinagajipara2012@gmail.com",
  "rishisharma132007@gmail.com",
  "pdiya5828@gmail.com",
  "hitendrasinh2004@gmail.com",
  "vaghamshimeet05@gmail.com",
  "kadamnagadrakshayani@gmail.com",
  "nikitaprajapati2004@gmail.com",
  "patelhet014@gmail.com",
  "ankitkumar048123@gmail.com",
  "deekshak2103@gmail.com",
  "bhayanimahhek@gmail.com",
  "jaiminbpatel0612@gmail.com",
  "damordhyey727@gmail.com",
  "shahprincy9586@gmail.com",
  "aadilthelearner369@gmail.com",
  "abhishek040478@gmail.com",
  "davepriyansh169@gmail.com",
  "chotaliyaraj21@gmail.com",
  "ziyathakor09@gmail.com",
  "jaindhruvi369@gmail.com",
  "hasantasneem859@gmail.com",
  "drastirewani@gmail.com",
  "akanksha25705@gmail.com",
  "adityakalal5053@gmail.com",
  "kushmistry22@gmail.com",
  "kotvalhimanshu4114@gmail.com",
  "radhikat671@gmail.com",
  "2402030430007@silveroakuni.ac.in",
  "anjnajagatiya@gmail.com",
  "rajputsamir2002@gmail.com",
  "ajv545@gmail.com",
  "avinashkourani2@gmail.com",
  "patelpoojan863@gmail.com",
  "naman18075@gmail.com",
  "akshaydamasiya355@gmail.com",
  "221260116058setiit@gmail.com",
  "jadavduneja786@gmail.com",
  "kashyap.rachit2019@gmail.com",
  "sadafshaikhh67@gmail.com",
  "vaghelanisarg6@gmail.com",
  "fatemamshaikh04@gmail.com",
  "rukhminadipak@gmail.com",
  "shahnavya2005@gmail.com",
  "priyankahjavani23@gmail.com",
  "vroy46732@gmail.com",
  "meet22patel44@gmail.com",
  "mmaruffatema@gmail.com",
  "salikshaikh1307@gmail.com",
  "prathammodi282@gmail.com",
  "dhruvbhatt7781@gmail.com",
  "rnnisarg7@gmail.com",
  "shahpratham538@gmail.com",
  "Kashyap.rachit2019@gmail.com",
  "pruthvirajdayma09@gmail.com",
  "abedabanuvijapura@gmail.com",
  "sohelkhanpathan757@gmail.com",
  "220140107031patelabhay@gmail.com",
  "roshanpatel3315@gmail.com",
  "patelmeet6699@gmail.com",
  "sarahbhuta65@gmail.com",
  "Malekmadina.123@gmail.com",
];

/**
 * Checks if an email is in the verified email list
 * Performs case-insensitive comparison for reliability
 * @param email - The email address to verify
 * @returns boolean - true if email is verified, false otherwise
 */
export function isEmailVerified(email: string): boolean {
  if (!email || typeof email !== "string") {
    return false;
  }

  // Normalize email: trim whitespace and convert to lowercase
  const normalizedEmail = email.trim().toLowerCase();

  // Create normalized version of verified email list for comparison
  const normalizedVerifiedEmails = VerifiedEmailList.map((verifiedEmail) =>
    verifiedEmail.toLowerCase().trim()
  );

  return normalizedVerifiedEmails.includes(normalizedEmail);
}

/**
 * Gets the total count of verified emails
 * Useful for admin purposes or displaying statistics
 * @returns number - Total count of verified emails
 */
export function getVerifiedEmailCount(): number {
  return VerifiedEmailList.length;
}